

import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import { Providers } from "../store/provider";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
        

         
            {children}{" "}
        
        
        </Providers>
      </body>
    </html>
  );
}
