

import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import { Providers } from "../store/provider";
import Nav from "../../components/Nav/nav";
import Topbar from "../../components/Nav/topbar";
import NoOperators from "../../components/Nooperators/noOperators";
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <Nav></Nav>
          <Topbar></Topbar>
          <NoOperators></NoOperators>
          <div className="ml-[200px] sm:ml-0 mt-[150px] sm:overflow-x-hidden overflow-x-auto">{children} </div>
        </Providers>
      </body>
    </html>
  );
}
